### ISSUE TITLE
white on white output for humidity, wind speed, cloud coverage and pressure

### ISSUE THREAD

**Issue by millette** [genuinetools/weather#15]
I just tried your weather cli and it's great!

I couldn't see the humidity for Montreal, so I changed to New York, same thing. Turns out the humidity (and other values) are there, but they are white on white with rxvt (white background). When I copy/paste the white text. I see the output is actually there.

An option to change the color scheme or some other form of autodetection would be appreciated.

**Comment by jonathanGB** [comment]
Happens with *solarized light* theme too!

<img width="864" alt="image" src="https://user-images.githubusercontent.com/8869660/35021308-49d3927c-fafe-11e7-8bf5-b89008f235bb.png">

**Comment by vielmetti** [comment]
Looks like the changes should be isolated to forecast/print.go https://github.com/genuinetools/weather/blob/master/forecast/print.go
