### ISSUE TITLE
VERSION and version/ overlap

### ISSUE THREAD

**Issue by FiloSottile** [genuinetools/weather#40]
OMG it took me forever to figure out why checking out `VERSION` was deleting `version/version.go`.

*Jess uses Linux of course.*

Please rename one of the two for your macOS friends ✨

**Comment by jessfraz** [comment]
ugh ya I do this in all my projects I am _the worst_ I gotta fix my project generator to be more considerate to the macOS peepsssss

**Comment by jessfraz** [comment]
I changed this in a different way for all my repos, sorry, thanks!
