### ISSUE TITLE
Google Geocode API Limit

### ISSUE THREAD

**Issue by espinielli** [genuinetools/weather#54]
I tried the example in the README and got issues with Geocode API:

```
weather -l "Paris, France" -u si
Geocode API response error: Google Geocode API response error: OVER_QUERY_LIMIT - You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account
```

Something to do on user or on software side (or both)?

**Comment by jessfraz** [comment]
its on the server side, sorry I do it as a free service so sometimes we hit a limit, you can always host your own :)

**Comment by vielmetti** [comment]
Also seeing this (no big deal).

Is there any way to bypass the geolocation routine if you know exactly where you want the weather from? So geocode externally, then pass in something like

`weather --latitude 42.27756 --longitude -83.74088`

I'll look at the code....
