### ISSUE TITLE
Forecast response failed

### ISSUE THREAD

**Issue by justisGipson** [genuinetools/weather#65]
Getting `Decoding forecast response failed: invalid character 'd' looking for beginning of value` message.
running:
`go version go1.11.4 darwin/amd64`
weather: 
`version     : v0.15.6`

had this error a few days ago, updated go version and it started to work. This morning was a different story.

**Comment by rwaight** [comment]
I'm getting this error as well: `Decoding forecast response failed: invalid character 'd' looking for beginning of value`

version information:
```
weather:
 version     : v0.15.6
 git hash    : homebrew
 go version  : go1.11.1
 go compiler : gc
 platform    : darwin/amd64
```

**Comment by nicholasarvelo** [comment]
I'm also getting `Decoding forecast response failed: invalid character 'd' looking for beginning of value`

**Comment by Calinou** [comment]
I can confirm this, I'm getting a slightly different error message though:

```
Http request to https://geocode.jessfraz.com/forecast failed with status code: 403
```

**Comment by justisGipson** [comment]
Does this happen about 50-70% of the time for the others experiencing this issue?

**Comment by Calinou** [comment]
It's working again here (as of writing) :slightly_smiling_face:

**Comment by claman** [comment]
It seems like it happens before noon for me

**Comment by justisGipson** [comment]
Definitely all times of the day for me, 2 days ago ran `weather -c` for current forecast and it worked. Few minutes later ran `weather -d 3` for 3 day outlook and got the error.

**Comment by krry** [comment]
Trying for the first time today, seeing:
`Http request to https://geocode.jessfraz.com/forecast failed with status code: 403`

Have my own API keys, anyone figured out how to self-serve?

**Comment by dimensi0n** [comment]
Same error `Decoding forecast response failed: invalid character 'd' looking for beginning of value`

**Comment by justisGipson** [comment]
Realized this is still open... I'm closing it. Don't think we ever heard from the maintainers on this ¯\_(ツ)_/¯
